apiVersion: v1
kind: Namespace
metadata:
  name: ${IMAGE_NAME}-dev
  labels:
    name: ${IMAGE_NAME}-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namspace: ${IMAGE_NAME}-dev
  name: ${IMAGE_NAME}-deployment
  labels:
    app: ${IMAGE_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${IMAGE_NAME}
    spec:
      containers:
      - name: ${IMAGE_NAME}
        image: ${IMAGE_REPO}${IMAGE_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namspace: ${IMAGE_NAME}-dev
  name: ${IMAGE_NAME}-service
spec:
  type: LoadBalancer
  selector:
    app: ${IMAGE_NAME}
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namspace: ${IMAGE_NAME}-dev
  name: ${IMAGE_NAME}-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ${IMAGE_NAME}-service
            port:
              number: 80